# action.yml
name: 'PixelGraph-Publish'
description: 'Publishs a PixelGraph project into a game-ready resource pack zip.'
author: null511
branding:
  icon: archive
  color: orange
inputs:
  project:
    description: 'The filename of the project to publish.'
    default: 'project.yml'
    required: true
  profile:
    description: 'The name of the publish profile within the project to use.'
    required: true
  zip:
    description: 'The filename of the published zip file.'
    default: 'release.zip'
    required: true
runs:
  using: 'docker'
  image: 'docker://null511/pixelgraph'
  args:
    - 'publish'
    - '-p'
    - '${{inputs.project}}'
    - '-n'
    - '${{inputs.profile}}'
    - '-z'
    - '${{inputs.zip}}'
