# action.yml
name: 'PixelGraph-Publish'
description: 'Publishs a PixelGraph project into a game-ready resource pack.'
author: null511
branding:
  icon: archive
  color: orange
inputs:
  profile:
    description: 'The filename of the publish profile to use.'
    required: true
  zip:
    description: 'The filename of the published zip file.'
    default: 'release.zip'
    required: true
runs:
  using: 'docker'
  image: 'docker://null511/pixelgraph'
  args: 'publish -p "${{inputs.profile}}"" -z "${{inputs.zip}}"'
